### ISSUE TITLE
no known way to get current pricing of a product?

### ISSUE THREAD

**Issue by tzmanish** [Tectors/EpicGraphQL#1]

**Comment by Tectors** [comment]
Hey, yeah sure I'll try to find it, also I just want to make sure that you still want this, so could you reply.

**Comment by Tectors** [comment]
Could you reply please?

**Comment by Tectors** [comment]
I'll work on it lol.

**Comment by Tectors** [comment]
Found it a month later.

**Comment by Tectors** [comment]
https://github.com/Tectors/EpicGraphQL/blob/main/docs/graphql/operation/getCatalogOffer_get.graphql
try it.
