### ISSUE TITLE
Upcoming promotions

### ISSUE THREAD

**Issue by woctezuma** [Tectors/EpicGraphQL#2]
Apparently, some people have been able to get upcoming promotions using the API.
This should allow to have a peek at upcoming free games.

I imagine this is done with https://github.com/Tectors/EpicGraphql/blob/main/docs/graphql/catalog/searchStoreQuery.graphql

However, when I try, e.g. with this request:
> https://www.epicgames.com/graphql?query={%20Catalog%20{%20searchStore%20{%20paging%20{count%20total}%20elements%20{%20title%20promotions%20{upcomingPromotionalOffers%20{%20promotionalOffers%20{startDate}%20}}%20}%20}%20}%20}

then:
- there are `403 Forbidden` errors

> "{\"errorCode\":\"errors.com.epicgames.common.missing_permission\",\"errorMessage\":\"Sorry your login does not posses the permissions 'priceengine:shared:promotionrule READ' needed to perform the requested operation\",\"messageVars\":[\"priceengine:shared:promotionrule\",\"READ\"],\"numericErrorCode\":1023,\"originatingService\":\"com.epicgames.priceengine.public\",\"intent\":\"prod\",\"errorStatus\":403}"

- the `promotions` are `null`.

I think this is what you warned about in https://github.com/Tectors/EpicGraphql/tree/main/docs/graphql#authorization
I have only discovered your repository now so I need to try what you mention in the README regarding the authorization.

Before that, I was:
- either spying on the requests made by browsing the store with Firefox dev tools,
- or more recently checking this [unofficial API documentation](https://github.com/SD4RK/epicstore_api/blob/master/epicstore_api/queries.py) to access Epic API with Python.

Would you have any idea how upcoming promotions could be accessed despite the authorization error?

**Comment by woctezuma** [comment]
Nevermind. This works for some reason. I did not bother checking all the entries for non `null` values.

**Comment by Tectors** [comment]
just if you didn't know it's because of the client for anybody getting the problem

**Comment by woctezuma** [comment]
> just if you didn't know it's because of the client for anybody getting the problem

I did not know that. I assume this is about:
https://github.com/MixV2/EpicResearch/blob/master/docs/auth/auth_clients.md

**Comment by woctezuma** [comment]
Re-opening the issue because of the comment regarding authorization.

Is the client ID sufficient? Because I see that the secret is not known for the client `graphqlWebsite`:
![Secret](https://i.ibb.co/vv8xCLM/2021-12-26-14-49-30.png)

If I need both client ID and secret, then I will have to use one of the `Kairo` clients:
![Kairo](https://i.ibb.co/YXYK2RD/2021-12-26-14-51-39.png)

**Comment by Tectors** [comment]
graphqlWebsite is literally used for the graphql website to get a token
soooo dumb

**Comment by Tectors** [comment]
Let me look at my 2020 code. Just wait.

**Comment by Tectors** [comment]
It should work? Try it.

**Comment by woctezuma** [comment]
Wait, so do you only need the client id for GraphQL? Is there no need for a secret to pass as the `graphqlWebsite` client?

You just pass the `code` returned by `https://www.epicgames.com/id/api/redirect` as a `code` parameter in your query to `https://www.epicgames.com/graphql`.

Is that it? No need to query `https://account-public-service-prod.ol.epicgames.com/account/api/oauth/token` for OAuth, etc.?

**Comment by Tectors** [comment]
There was a version of the GraphQL which you could literally just login in log out and it would generate the graphqlWebsite I believe.

https://web.archive.org/web/20200208114405/https://graphql.epicgames.com/
![image](https://user-images.githubusercontent.com/73559984/147413654-0527b525-daca-40ce-bebd-2b3734483068.png)

**Comment by Tectors** [comment]
Don't go to the [GraphQL login page](https://www.epicgames.com/login), it'll forever loop you.

**Comment by woctezuma** [comment]
Ok. Thank you!

Strangely, it seems I don't need the authentication code. The authentication error only appears for:
- https://www.epicgames.com/graphql
and not for:
- https://graphql.epicgames.com/graphql

**Comment by Tectors** [comment]
You got it fixed? Nice.

**Comment by woctezuma** [comment]
I think so. As you mentioned, the code returned by the redirect URL is the code, no need for OAuth.

Plus, the URL matters: replacing `www` with `graphql` changes some things. 👍
