### ISSUE TITLE
Graphql -> GraphQL

### ISSUE THREAD

**Issue by Revadike** [Tectors/EpicGraphql#3]
It kinda bothers me enough to make an issue about it. I think this is how most would write GraphQL. Also, I have a collection epicgames graphql queries and mutations from 2020, I could share with you. DM me, if you want: revadike[at]outlook[dot]com.

**Comment by Tectors** [comment]
Sorry, I guess I forgot.
Funny thing is that I literally switch between them.

**Comment by Tectors** [comment]
(emailed you at toutinrogel@gmail.com)

**Comment by woctezuma** [comment]
Looking forward to see what comes out of this. :)

**Comment by Tectors** [comment]
I did this before: https://github.com/Tectors/EpicGraphQL/tree/f6c897e045a86f9ea40cb06795538e594ff7fa02/docs/account/operations

I probably will do it later on but I want to work on my request parser.
