### ISSUE TITLE
README was deleted

### ISSUE THREAD

**Issue by woctezuma** [Tectors/EpicGraphQL#4]
Not sure if on purpose:
- https://github.com/Tectors/EpicGraphQL/commit/ad9cc763aaf6b42cbac5afab46d745e82400a9b9

**Comment by woctezuma** [comment]
Actually, I am experiencing a display issue with the main README, which is not the (mostly empty) one which was deleted.

![Bug](https://i.ibb.co/2F2VdH5/2021-12-26-09-14-56.png)

**Comment by Tectors** [comment]
The main README was never created from this version, and also in the commit I deleted the empty README in the store folder.

**Comment by Tectors** [comment]
(a README to the main directory will be added tomorrow as I am thinking of ideas)

**Comment by Tectors** [comment]
Working on it :).
